from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c386e4052be"
down_revision = "713af8a4cb34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column("enable_downloads", sa.Boolean(), nullable=True, default=False),
    )
    op.execute("UPDATE invoices SET enable_downloads = False")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "enable_downloads")
    # ### end Alembic commands ###